# -*- coding: utf-8 -*-
"""Point-by-point response to reviewer comments XL10 to XL16.

Numbers for XL14 to XL16 come from xl1416_content (the same source as Appendix A and the
manuscript changes). Numbers for XL10 to XL13 come from Appendix C as delivered on
2026-09-29 (附录C_多模块验证与开销_20260929.docx).

  python scripts/diagnostics/xl1016_response_letter.py
"""
from __future__ import annotations

import sys
from pathlib import Path

from docx import Document
from docx.shared import Pt

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "scripts/multi_module"))
sys.path.insert(0, str(Path(__file__).resolve().parent))
from mm_docx import style_run  # noqa: E402
from xl1416_content import build_content, fmt_p, pc, pcw  # noqa: E402

OUT = ROOT / "回复审稿人_LiXiao_XL10-16_20260930.docx"

COMMENTS = {
    "XL10": "The empirical evidence comes from a single Type A module in one Hong Kong project. This is insufficient to claim generalizability. Add multiple modules, multiple factories, or at least multiple projects/regions. Compare calculated totals against manual LCA or an existing BIM-LCA tool to validate carbon accounting correctness, not only QA accuracy.",
    "XL11": "The paper states that shared energy can remain unattributed to any product object and appears only in the process perspective. If so, the sum of product-perspective totals may not equal the process-perspective total, and the “total carbon of a modular unit” may undercount shared factory emissions. Define the allocation policy precisely, justify mass-share allocation for energy, provide reconciliation equations, and include sensitivity analysis for alternative allocation rules.",
    "XL12": "Carbon results depend on emission factors, EPD choices, allocation assumptions, missing quantities, and rejected records. The paper mentions eight rejected material records but does not quantify their impact. Add uncertainty analysis or scenario analysis for emission factors, allocation methods, and data gaps. Report data quality indicators and how they affect totals and rankings.",
    "XL13": "The case graph has only 2,993 nodes and 5,613 edges for one Type A module. The building contains 873 modules. Reviewers will ask whether the approach scales to a whole building or multiple projects. Report graph construction time, query latency, memory, token cost, and API cost. Test with multiple module types, larger graphs, and concurrent users.",
    "XL14": "Please report how questions were generated, annotator agreement, difficulty distribution, and whether the benchmark was used during prompt development. If yes, there is a risk of data leakage. Also report prompt templates, token budgets, retries, temperature, model versions, and whether baselines received equivalent prompt engineering. Add a human expert baseline or a manual-query baseline.",
    "XL15": "Put it into appendix.",
    "XL16": "The paper reports aggregate pass rates but not enough diagnostic detail. Separate compiler errors from executor errors, data errors, boundary-state errors, and perspective-classification errors. Report precision/recall/F1 for perspective, source scope, and operation classification. Ablate the type validator, the graph, the executor, and the LLM compiler to show each layer’s contribution. Use paired statistical tests across configurations.",
}


def build_responses(C) -> dict:
    D3 = __import__("json").loads((ROOT / "outputs/research_experiments/diagnostics_20260930/D3_report/diagnostics.json").read_text(encoding="utf-8"))
    rates, tax, slots, pairs, ho, kf = D3["rates"], D3["error_taxonomy"], D3["slots"], D3["paired_tests_150"], D3["heldout_rule_vs_llm"], D3["keyfree_numeric_90"]
    fs = D3["full_system_subsets"]
    st, ref = C.facts["stages"], C.facts["ref"]
    bs = tax["full_real"]["boundary_split"]
    cons = bs["conservative (reference executable, returned a boundary state)"]
    n_fail = C.facts["n_fail_full"]
    kappa = __import__("json").loads((ROOT / "outputs/research_experiments/diagnostics_20260930/D5_human_tasks/annotation_sheet_40_kappa.json").read_text(encoding="utf-8"))
    A = C.labels.app
    R = {}
    R["XL10"] = [
        "We agree that one module is a narrow evidence base. The revised case study covers three module types of the same building, Type A, Type B and Type D. Section 4.1.1 describes the two additional IFC models and their preprocessing, the removal of building-services elements, the assignment of materials through the type-level material rules of the Type A model, and the reclassification of one Type B structural slab that had been exported as a generic proxy. Section 4.1.2 and Table 2 report the statistics and quality of the three graphs, and Section 4.1.3 and Table 3 report their carbon accounts, 6,557, 6,048 and 6,828 kgCO2e from the product perspective, or 322, 303 and 335 kgCO2e per square metre of floor slab.",
        "The correctness of the accounting is verified in two ways that are independent of the graph builder (Appendix C.2). A spreadsheet recomputes every accepted material record from the stored design quantity, thickness, density and selected factor and reproduces the graph totals of all three modules to within 1e-12 kgCO2e, and an independent reviewer recalculated 47 sampled records of the Type A module, 30 material and 17 energy, at a tolerance of 1 percent, and all 47 passed. We did not compare the totals against a commercial BIM-LCA tool, because such a comparison would combine differences in factor databases and in quantity take-off with differences in the accounting itself and would not isolate the correctness of the accounting. The effect of the factor choice is reported separately as scenarios in Appendix C.3.",
        "On generalisability, the three module types share one project and one factory, and Section 5.2 now states this scope. The results show that the ontology and the compiler transfer across module types within a project, and they do not show transfer across projects, factories or regions. The transfer test in Section 4.3.5 and Appendix C.6 supports the within-project claim. With the compiler, its prompt and its worked examples frozen on Type A, held-out questions on Type B and Type D reach 70.8 percent exact answers against 66.7 percent on Type A, 30 of the 48 questions are solved on all three graphs and 13 fail on all three. Data from other factories or projects were not available to us for this revision.",
    ]
    R["XL11"] = [
        "The reviewer is right that the earlier text left the allocation policy and the relation between the perspective totals implicit. Section 3.1.3 now defines the policy. Each energy record falls in one of three classes. A record whose factory log names a component or a module is a direct record and its full value enters the product perspective of that target. A record with declared shares for the modules of the production batch is a shared record and the declared shares distribute its value across those modules. The shares follow module mass, which is the physical relationship between the shared energy and the products that ISO 14044 ranks before any economic relationship, and the factory reports its own energy allocation on the same basis. A shared record without a declared share for the module is a process-only record and enters the process perspective alone.",
        "Equations 4a and 4b give the reconciliation. The product perspective total equals the material term plus direct energy plus energy allocated to the module, and the process perspective total equals direct energy plus the energy allocated to this module plus the energy allocated to the other modules of the batch plus process-only energy. Section 4.1.3 and Table 3 report every term for the three modules, and both identities close to within 1e-12 kgCO2e in all three accounts. The product perspective total is therefore the carbon a module carries, and the factory energy that no module carries, 1,021 to 1,045 kgCO2e per graph, is counted once at factory level. Equation 11 in Section 5.1 states the resulting building account, in which the shared term enters once, so the building total does not undercount shared emissions.",
        "Sensitivity to the allocation rule is reported in Appendix C.1, Table C2, and plotted in the new figure of Section 4.1.3. Re-allocating the shared meters by production duration shares, machine-hour shares or equal shares moves the allocated term within 17 percent of its mass-share value, moves the product totals by at most 0.4 percent and leaves the order of the three module types unchanged.",
    ]
    R["XL12"] = [
        "We added the scenario, data gap and data quality analyses the reviewer asks for in Appendix C.3 to C.5, with a summary paragraph in Section 5.1 that orders the sources of uncertainty.",
        "Emission factors (Appendix C.3, Table C3). Replacing the selected Hong Kong localised factors by the original database values raises the product perspective totals by 1.2 to 1.5 percent. A 10 percent change of the steel factor moves the totals by 6.6 to 6.8 percent, and the same change of the calcium silicate or the concrete factor moves them by 1.0 to 1.5 percent. The national life-cycle electricity factor raises the totals by 1.0 to 1.1 percent and the CO2-only provincial factor lowers them by 0.7 to 0.8 percent. Restricting diesel to its combustion emissions lowers the process perspective by 7 percent and leaves the product perspective unchanged, because diesel enters through process-only records. The order of the three module types and the position of steel as the largest material hold in every scenario. Calcium silicate and concrete differ by 2 percent in Type A and 8 percent in Type B and change order under a 10 percent change of either factor, and Table C3 reports this.",
        "Allocation methods (Appendix C.1, Table C2). See our response to XL11.",
        "Rejected records (Appendix C.4, Table C4). The pipeline rejected eight material records in Type A, eight in Type B and seven in Type D, the toughened glass of the windows and the ceramic tiles of the two toilet floors, and in Type D also the calcium silicate board of one partition. Treating each window opening as one 6 millimetre glass pane and each other component as made entirely of the rejected material at its full model volume bounds their carbon at 145, 145 and 433 kgCO2e, that is 2.3, 2.5 and 6.7 percent of material carbon, and adding the bound to any total leaves the order of the types unchanged.",
        "Data quality indicators (Appendix C.5, Table C5). Every data source of the account is rated on the time, geography and technology criteria of EN 15804 and the ecoinvent pedigree matrix, with its share of the account and its effect on totals and rankings. The steel factor carries about 70 percent of material carbon and dates from 2013, which is the main quality gap and is now stated in Section 5.2. Section 5.1 orders the sources, the steel factor first, the production route assumption for Type B and Type D second, up to 4.1 percent, and the allocation rule third.",
    ]
    R["XL13"] = [
        "Appendix C.7, Table C7, reports the cost figures the reviewer lists for each of the three module graphs, and Section 4.3.5 summarises them. Building a module graph takes 15 to 17 seconds and loading it adds 57 to 59 megabytes to the process memory. Compiling a question takes 2.4 to 2.9 seconds on average and 3.9 to 4.8 seconds at the 95th percentile, with 1.4 language model calls, about 2,440 prompt tokens and 194 completion tokens per question, and an API cost of 0.0008 US dollars per question, 0.11 US dollars for the 150-question benchmark at the list price of DeepSeek-chat. Executing a compiled programme on the in-memory graph takes 0.5 to 1.3 seconds. Compilation cost does not depend on graph size, because the prompt carries the operator contract, the schema and the worked examples and not the data, and the three graphs show the same token counts.",
        "On scaling to the whole building, Section 5.1 now makes the argument explicit. A modular building repeats a small number of module designs, each with one IFC model and one production route, so the building account follows from the type accounts and the module schedule, Equation 11, and the knowledge graph holds one graph per module type together with the schedule and not one copy per module. Section 4.1.3 and Appendix C report the three types. We did not build a synthetic graph of 873 modules and we did not test concurrent users, and Section 5.2 states that the cost figures come from a single user and that concurrent access was not tested.",
    ]
    R["XL14"] = [
        f"We agree and, following XL15, we have placed this material in a new {A} with a pointer from Section 4.3.1, where a new table of evaluation measures, Table 4, defines the strict pass rate, status accuracy, strict numeric accuracy and any-hit rate with their question sets and denominators.",
        f"Question generation and reference answers ({A}.1). Questions were generated for every cell of the perspective by operation by response-state matrix from the frozen graph release, so every reference number and state is computed from the release and is reproducible from it. The template wording was rewritten into natural questions by DeepSeek-chat at temperature 0 and revised by the authors in seven review rounds. The benchmark version, its SHA-256 hash and the lineage of frozen versions are stated.",
        f"Annotator agreement ({A}.2, Table A2). A doctoral researcher in the same field labelled 40 stratified questions blind, with the question text and the viewer selection only. Agreement with the reference labels is κ = {kappa['perspective']['kappa']:.2f} for the perspective and κ = {kappa['operation']['kappa']:.2f} for the operation. For the response state κ is {kappa['status']['kappa']:.2f}, because the annotator labelled {C.facts['marked_exec']} of {kappa['status']['n']} questions executable. The state depends on what the graph release holds for the named target and cannot be read from the question alone, so we report the reference states as properties of the question against the release, computed by executing the reference programme, and not as human judgements.",
        f"Difficulty distribution ({A}.1, Table A1). The table gives the perspective by operation counts split into executable and boundary questions, the reference states of the 60 boundary questions, the three difficulty tags, single_hop 74, multi_hop 60 and batch_allocation 16, and the scope split, 106 project questions and 44 questions asked with BIM items selected in the viewer.",
        f"Prompt development and leakage ({A}.3, and stated in Section 5.2). The compiler contract, its rule list and its three worked examples were developed while the 150 questions were available and the compiler was run on them, so the 150-question set is a development set and the figures of Sections 4.3.2 to 4.3.4 are development-set figures. No benchmark question appears in a prompt and no worked example is a benchmark question. The held-out sets of Appendix C.6, 48 new questions per module written after the contract was frozen and sharing no question with the 150, are the test on unseen wording.",
        f"Prompt templates and settings ({A}.4, {A}.5). Table A3 gives the model, the temperature of 0, the 1,800-token output limit of the compiler and repair calls, the timeout and retry rule, the response format, the repair and semantic-gate stages, the number of runs and the dates of every configuration. {A}.5 reproduces verbatim the compiler system prompt, the 19 contract rules, the three worked examples, the repair prompt and the three baseline prompts, with the size of the tables embedded in each baseline prompt.",
        f"Baseline prompt engineering ({A}.6). The baselines share the model, the temperature and the graph release with the full system. Each receives a task preamble, the data as JSON tables with a note on what is precomputed, and, for the structured baseline, an output-format instruction and a JSON response format. They contain no CarbonQL syntax, no validator and no worked example, and we state this in place of a claim of equivalent prompt iteration. We also corrected the tolerance statement of Section 4.3.4 to the protocol applied to prose answers, a relative tolerance of 10⁻³ or 0.01 kgCO2e absolute, and we report the strict pass rate of the full system on the same 90 questions, {pc(fs['executable_pass'])} percent, next to its {pc(kf['full_real']['strict_all_mean'])} percent strict numeric accuracy.",
        f"Manual-query baseline ({A}.7, Table A5). We added a hand-written rule compiler, deterministic cue-word and gazetteer rules written by an author with access to the graph vocabulary, which maps each question to a CarbonQL programme without any language model and runs through the same validator, executor and scorer. It reaches {pcw(rates['rule_compiler']['pass_mean'])} strict pass on the 150 questions against {pcw(fs['pass_mean'])} for the full system, McNemar p = {fmt_p(pairs['rule_compiler']['majority_vs_majority']['mcnemar_p'])}, and {pc(ho['A']['rule_exact'])} to {pc(ho['B']['rule_exact'])} percent exact answers on the held-out sets against {pc(ho['A']['llm_exact_majority'])} to {pc(ho['B']['llm_exact_majority'])} percent for the frozen language model compiler. We did not run a per-question human expert study. The human element of the evaluation is the blind annotation of {A}.2.",
    ]
    R["XL15"] = [f"Done. All of the material requested in XL14 is in {A}, and Section 4.3.1 carries only the table of measures and a pointer."]
    stage_txt = ""
    if C.facts["have_stages"] and ref:
        stage_txt = (f"On the 150 questions the strict pass rate is {pc(st['V1']['pass'])} percent without the typed contract, V1, where the validator rejects on average {st['V1']['compile']:.0f} of the 150 first programmes, {pc(st['V2']['pass'])} percent with the contract, V2, {pc(st['V3']['pass'])} percent with the validator-driven repair call, V3, and {pc(ref['pass'])} percent with the semantic coverage gate, V4, in the re-compiled reference arm. "
                     f"The validator cannot be removed on its own, because the executor enforces the same typing rules, and executing the rejected programmes without validation raises the same typing errors in the executor in every case, so its contribution is the rejection code that drives the repair call and the semantic gate. ")
    R["XL16"] = [
        f"Error classes ({A}.8, Table A6, summarised in Section 4.3.2). Every failed answer is classified in a fixed order as a compile error, an executor error, a boundary-state error, a perspective error, an operation error or a value or target error. Of the {n_fail} failures of the full system over three runs, none is a compile or executor error, {tax['full_real']['counts']['boundary_state_error']} are boundary-state errors, {cons} of them conservative in that the graph supported an answer and the system returned incomplete_path or empty_result, {tax['full_real']['counts'].get('perspective_error', 0)} are perspective errors, {tax['full_real']['counts'].get('operation_error', 0)} operation errors and {tax['full_real']['counts'].get('value_or_target_error', 0)} value or target errors. Data errors do not form a class, because the reference is computed from the same release, so a gap in the data changes the reference state and the answer alike. The rejected records are quantified in Appendix C.4.",
        f"Precision, recall and F1 ({A}.9, Table A7). We report the perspective and the operation at two levels, the answer level, macro F1 {pc(slots['full_real']['perspective']['macro']['f1'])} and {pc(slots['full_real']['operation']['macro']['f1'])} percent, and the programme level read from the compiled programme, {pc(slots['full_real (program level)']['perspective']['macro']['f1'])} and {pc(slots['full_real (program level)']['operation_raw']['macro']['f1'])} percent, together with the entity scope from the selector and the emission-source set on the held-out sets, where the compiler selects the reference source set for {pc(slots['emission_source (held-out, LLM V4, program level)']['A']['accuracy'])} percent of the Type A questions and {pc(slots['emission_source (held-out, LLM V4, program level)']['B']['accuracy'])} percent of the Type B and Type D questions. Both levels are given so that the answer-level rates are not read as compiler accuracy.",
        f"Ablations ({A}.10, Table A8, summarised in Section 4.3.4). The type validator and the compiler stages are ablated on the same 150 questions with the four compiler variants of Appendix C.6. {stage_txt}"
        f"The graph is ablated by the LLM-only baseline, {pcw(kf['llm_only_real']['strict_all_mean'])} strict numeric accuracy against {pcw(kf['unconstrained_kg_llm_real']['strict_all_mean'])} for the same model reading the graph. The executor is ablated by the two graph baselines against the full system, {pcw(kf['full_real']['strict_all_mean'])}. The language model compiler is ablated by the hand-written rule compiler of {A}.7. The two control policies, status blocking and the provenance constraint, change the outcome of at most one question per run, because they govern what the answer discloses and not the number it returns, and Appendix A.10 states this.",
        f"Paired tests. Every comparison in Sections 4.3.2 and 4.3.4 and in {A} now carries an exact McNemar test on the per-question outcomes, with the majority over runs, and a bootstrap 95 percent confidence interval of the pass rate. The full system against the knowledge graph prose baseline gives p = {fmt_p(kf['unconstrained_kg_llm_real']['paired_vs_full_majority']['mcnemar_p'])}, against the rule compiler p = {fmt_p(pairs['rule_compiler']['majority_vs_majority']['mcnemar_p'])}, and against the V1 compiler p = {fmt_p(st['V1']['p']) if st['V1'] else 'n/a'}. The test does not separate the repair call and the semantic gate from the full system on 150 questions, p = {fmt_p(st['V2']['p']) if st['V2'] else 'n/a'} and {fmt_p(st['V3']['p']) if st['V3'] else 'n/a'}, and it does separate the semantic gate step on the held-out set, p = 0.008, and we report both results.",
    ]
    return R


def main() -> None:
    C = build_content()
    R = build_responses(C)
    doc = Document()
    normal = doc.styles["Normal"]
    normal.font.name = "Times New Roman"
    normal.font.size = Pt(11)
    style_run(doc.add_paragraph().add_run("Point-by-point response to comments XL10 to XL16"), bold=True, size=13)
    doc.add_paragraph("We thank the reviewer for the detailed comments on the case study and on the evaluation. In response we have extended the case to three module types, verified and reconciled the carbon accounts, added scenario, data gap, data quality and cost analyses, and rewritten the evaluation reporting with a new Appendix A. Each comment is reproduced in full below, followed by our response and the location of the change. New or changed text in the revised manuscript is marked in red, and Appendix A and Appendix C are supplied as separate files.")
    for key in ("XL10", "XL11", "XL12", "XL13", "XL14", "XL15", "XL16"):
        style_run(doc.add_paragraph().add_run(f"Comment {key}"), bold=True)
        p = doc.add_paragraph()
        style_run(p.add_run(COMMENTS[key]), italic=True)
        style_run(doc.add_paragraph().add_run("Response"), bold=True)
        for para in R[key]:
            doc.add_paragraph(para)
    doc.save(OUT)
    print("written:", OUT)


if __name__ == "__main__":
    main()
